# Generated by Django 4.2.3 on 2023-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FcUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=64, verbose_name="사용자 이름")),
                ("password", models.CharField(max_length=64, verbose_name="비밀번호")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록 시간"),
                ),
            ],
            options={"db_table": "fastcampus_fcuser",},
        ),
    ]
