# Generated by Django 4.2.3 on 2023-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_fcuser_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fcuser",
            options={
                "verbose_name": "패스트캠퍼스 사용자",
                "verbose_name_plural": "패스트캠퍼스 사용자들",
            },
        ),
        migrations.AddField(
            model_name="fcuser",
            name="user_email",
            field=models.CharField(
                default="test@gmail.com", max_length=128, verbose_name="사용자 이메일"
            ),
            preserve_default=False,
        ),
    ]
